# Generated by Django 4.1.7 on 2023-02-22 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cour_nom', models.CharField(max_length=128)),
                ('cour_date_debut', models.DateTimeField(verbose_name='Date de début du cour')),
                ('cour_date_fin', models.DateTimeField(verbose_name='Date de fin du cour')),
                ('cour_nombre_places', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ecoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecole_nom', models.CharField(max_length=128)),
                ('ecole_adresse', models.CharField(max_length=128)),
                ('ecole_ville', models.CharField(max_length=128)),
                ('ecole_cp', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nom', models.CharField(max_length=64)),
                ('user_prenom', models.CharField(max_length=64)),
                ('user_date_naissance', models.DateTimeField(verbose_name='Date de naissance')),
                ('user_type_user', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(verbose_name='Date de la réservation')),
                ('id_cour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion_reservations.cours')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion_reservations.users')),
            ],
        ),
        migrations.AddField(
            model_name='cours',
            name='id_ecole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_gestion_reservations.ecoles'),
        ),
    ]
