# Generated by Django 4.1.7 on 2023-02-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_reservations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cours',
            new_name='Cour',
        ),
        migrations.RenameModel(
            old_name='Ecoles',
            new_name='Ecole',
        ),
        migrations.RenameModel(
            old_name='Reservations',
            new_name='Reservation',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
