# Generated by Django 4.1.7 on 2023-02-22 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion_reservations', '0002_rename_cours_cour_rename_ecoles_ecole_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id_ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_gestion_reservations.ecole'),
        ),
    ]
